### ISSUE TITLE
Persistent Mode / Git Mode not working

### ISSUE THREAD

**Issue by Validark** [evaera/RbxSync#1]
I have opened a place of mine and used the following:

``` lua
local Http = game:GetService("HttpService")
Http:ClearAllChildren()
Http.HttpEnabled = true
local StringValue = Instance.new("StringValue")
StringValue.Name = "PlaceName"
StringValue.Value = "Testing"
StringValue.Parent = Http
```

After restarting studio, and my computer, and the .exe client, there is still no RSync folder in Documents/ROBLOX. It keeps saving Temp files.

**Comment by evaera** [comment]
Can't reproduce. Please  attach the place you are trying to use and I'll try to test it with that.

**Comment by Validark** [comment]
It isn't working for any places. Are these instructions correct?
`To enable this feature, create a StringValue in HttpService named PlaceName, and then set the value to the name you'd like the folder to use. The scripts will then be written to C:\Users\<current user>\Documents\ROBLOX\RSync\<Place Name>. Note: You must re-open your game in Studio after you create this value. And, make sure you turned HttpEnabled on!
`

**Comment by evaera** [comment]
Yes. It works for me.

**Comment by Validark** [comment]
[Found the issue](https://github.com/evaera/RSync/blob/master/plugin/plugin.moon#L290).

For me at least, the `FindFirstChild` function would fire before the StringValue appeared in the HttpService, and thus `Http.PlaceName` didn't exist.

**Comment by Validark** [comment]
I got it to work for my client. Not the best solution, but...

``` moonscript
cp  = game\GetService "ContentProvider"
```

``` moonscript
repeat until cp.RequestQueueSize == 0 or not wait! -- Don't know how to do this in moonscript
if http\WaitForChild("PlaceName", 5) and http.PlaceName\IsA("StringValue") and #http.PlaceName.Value > 0
```

**Comment by evaera** [comment]
Will fix tomorrow.
