### ISSUE TITLE
[Fix coming in version 2] Editing in Studio with plugin crashes Rsync

### ISSUE THREAD

**Issue by Validark** [evaera/RbxSync#10]
All the time, when I try to edit a script in Studio while the Rsync plugin is open, the type position indicator goes to the very first spot on the first line, probably indicating that the plugin is overriding Script.Source while I am trying to type. This only happens when I am typing in Roblox Studio's editor and doesn't start until I have already typed a little bit.

This causes the plugin to repeatedly write to Script.Source, and usually ends in "Lost connection to helper client"

**Comment by cyberbum** [comment]
Hi,

I've had the same behavior, when I'm in studio, the cursor often resets to the top of the file. Once this happens the connection to the helper seems busted. I almost lost work done while using Visual Studio Code (thankfully I had backed up to github yay!) so nothing lost, but it was scary enough that I had to uninstall the plugin.

Any potential leads on what the bug would be? I really loved being able to edit in another editor, and the bonus was being to submit to Github (I'm not thrilled at only being able to submit the full rblx file, I much rather submit lua code)

**Comment by Validark** [comment]
I COULD do some bug tests and find the issue if the issue is Roblox side. If it's an issue with the coffeescript, there isn't much I can do. I just haven't taken the time because I have other things to work on and I don't feel like it's my responsibility. When my code doesn't work for other people, then I feel like it's my responsibility.

**Comment by Validark** [comment]
To me it looks like the plug-in is writing to Script.Source while you have it open, which is what I think "resets the cursor"
