### ISSUE TITLE
[Coming in version 2] Mapping specific files to scripts in Studio

### ISSUE THREAD

**Issue by GigsD4X** [evaera/RbxSync#12]
For preexisting projects, it'd be **extremely** useful to be able to map specific files to scripts in Studio, as opposed to the default behavior where files are generated automatically based on the game's hierarchy 🗺 

This would be mostly useful in cases where you're developing from repositories containing source code files that correspond to scripts somewhere in Studio, but are laid out arbitrarily and independent from their actual hierarchy (e.g. https://github.com/F3XTeam/RBX-Building-Tools).

There are probably security implications depending on the implementation, but even if it requires a small amount of effort on the user end to get working for each Studio session, it's still worth it since it eliminates the constant need to copy and paste code constantly to sync files, which interrupts _The Flow_ :tada:

**Comment by evaera** [comment]
👍 will put on version 2 to-do list

**Comment by Validark** [comment]
Good idea. Have encountered this situation myself. It would be very useful in version 2. Support.
