### ISSUE TITLE
RSync 1.3.1 no longer working on latest roblox.

### ISSUE THREAD

**Issue by ToastEngine** [evaera/RbxSync#15]
No output errors. Plugin no longer showing in plugins bar. Plugin still exists in the plugin folder though.

**Comment by GixxerK3** [comment]
I'm not sure exactly what evaera is trying to guard against but if you change line 380 of rsync.lua from:
```lua
if game.Name:match("Place[%d+]") and (game:GetService("RunService"):IsClient() and game:GetService("RunService"):IsServer()) then
```

to

```lua
if game:GetService("RunService"):IsStudio() and (game:GetService("RunService"):IsClient() and game:GetService("RunService"):IsServer()) then
```

it will get RSync working again. Seems to me like that's along the lines of what the original code was implying. 

I'm not certain that what she was after but I'll submit a pull request for it and see what happens.

**Comment by GixxerK3** [comment]
Actually, I see what she was after now and the code I gave isn't it. What I gave will get you editing again but Studio will crash when you run your game and then stop it. I'll see if I can figure out a better way...

**Comment by evaera** [comment]
I will investigate this when I get off work

**Comment by GixxerK3** [comment]
Got the pull request in. Hopefully that gets everything resolved.

In the meantime, you can change line 380 to the following 2 lines:

```lua
game:GetService("RunService").Heartbeat:Wait()
if (game:GetService("RunService"):IsStudio() and not game:GetService("RunService"):IsRunning()) and (game:GetService("RunService"):IsClient() and game:GetService("RunService"):IsServer()) then
```
