### ISSUE TITLE
Debug Error Causes Connection Loss

### ISSUE THREAD

**Issue by Xzensi** [evaera/RbxSync#29]
Whenever the roblox debugging console outputs some stack or error it causes the rbxsync to throw connection loss and the easiest way to restore this connection is to restart the rbxsync and restart the whole studio. This obviously destroys the workflow. 

Now when I reconnect the script with the plugin it'll create a new file with an incremented file name "filename (nth).lua", this prevents compilation of moonscript files without having to rename the .moon files too to "filename (nth).moon"

Editor: Sublime Text 3

![image](https://user-images.githubusercontent.com/14015478/36947608-cd772bda-1fce-11e8-84b1-85efa93bfb29.png)

**Comment by evaera** [comment]
Hey, sorry you are having trouble. A lot of Roblox updates have caused RbxSync to become unstable at certain times. I actually don't use the Lua debugger so I've never encountered this before. I'm not sure why this would be happening. Are you using temporary or persistent mode?

**Comment by Xzensi** [comment]
That's to be expected indeed. Roblox updated quite a bit since rbsync got some love. I'm using persistent mode.

**Comment by evaera** [comment]
While I continue to work on RbxSync v2, I recommend you check out https://github.com/osyrisrblx/RbxRefresh if you're still having trouble with this.
