### ISSUE TITLE
Allow users to configure the output directory

### ISSUE THREAD

**Issue by vocksel** [evaera/RbxSync#3]
Hi! I'm really interested in using RSync, but having a static output path is a big issue for me.

I like to keep a lot of my projects in Dropbox to keep them synced between computers, but from what I can tell the output directory is hardcoded under `Documents`. Would making this optional be a possibility?

With this change, I also propose the use of a ModuleScript to contain RSync's options, instead of using StringValues. This would go under HttpService like before, the name could be "RSyncConfig" or something similar.

``` lua
return {
  PlaceName = "Project",

  -- This determines the directory we sync from (defaults to Documents/Roblox/RSync). 
  -- PlaceName would be appended to this path.
  SyncFolder = "C:/Users/Username/Dropbox"
}
```

I'm debating whether to continue work on a current project or learn CoffeeScript and MoonScript so I can implement these changes myself, though I'm not sure if I have the time right now. I very much want to jump ship from my current workflow and RSync looks incredibly promising.

**Comment by evaera** [comment]
RSync could definitely use some more user friendly customization options. I think I will start working on a GUI interface that simplifies everything and adds a few more options.

Will start work on it tomorrow! (:

**Comment by vocksel** [comment]
Great to hear! I'll be keeping a close eye on this project, I'm really excited for all the future changes :)

**Comment by evaera** [comment]
Will probably look into adding more per-project settings in the future, but I worked for a really long time on this today so I thought i'd push it out. ;)
